# Generated by Django 3.2.2 on 2021-05-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleUzb', models.CharField(blank=True, max_length=200, null=True)),
                ('titleRus', models.CharField(blank=True, max_length=200, null=True)),
                ('titleEng', models.CharField(blank=True, max_length=200, null=True)),
                ('pictureURL', models.CharField(blank=True, max_length=2000, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph', models.TextField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleUzb', models.CharField(blank=True, max_length=200, null=True)),
                ('titleRus', models.CharField(blank=True, max_length=200, null=True)),
                ('titleEng', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraphUzb', models.TextField(blank=True, max_length=1000, null=True)),
                ('paragraphRus', models.TextField(blank=True, max_length=1000, null=True)),
                ('paragraphEng', models.TextField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('pictureURL', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleUzb', models.CharField(blank=True, max_length=200, null=True)),
                ('titleEng', models.CharField(blank=True, max_length=200, null=True)),
                ('titleRus', models.CharField(blank=True, max_length=200, null=True)),
                ('numberOfAllQuotasUzb', models.TextField(blank=True, max_length=1000, null=True)),
                ('numberOfAllQuotasRus', models.TextField(blank=True, max_length=1000, null=True)),
                ('numberOfAllQuotasEng', models.TextField(blank=True, max_length=1000, null=True)),
                ('numberOfStudentsAllUzb', models.TextField(blank=True, max_length=1000, null=True)),
                ('numberOfStudentsAllRus', models.TextField(blank=True, max_length=1000, null=True)),
                ('numberOfStudentsAllEng', models.TextField(blank=True, max_length=1000, null=True)),
                ('numberOfStudentsDailyUzb', models.TextField(blank=True, max_length=1000, null=True)),
                ('numberOfStudentsDailyEng', models.TextField(blank=True, max_length=1000, null=True)),
                ('numberOfStudentsDailyRus', models.TextField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUzb', models.CharField(blank=True, max_length=200, null=True)),
                ('nameRus', models.CharField(blank=True, max_length=200, null=True)),
                ('nameEng', models.CharField(blank=True, max_length=200, null=True)),
                ('informationUzb', models.TextField(blank=True, max_length=1000, null=True)),
                ('informationRus', models.TextField(blank=True, max_length=1000, null=True)),
                ('informationEng', models.TextField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleUzb', models.CharField(blank=True, max_length=200, null=True)),
                ('titleRus', models.CharField(blank=True, max_length=200, null=True)),
                ('titleEng', models.CharField(blank=True, max_length=200, null=True)),
                ('subTitleUzb', models.CharField(blank=True, max_length=200, null=True)),
                ('subTitleRus', models.CharField(blank=True, max_length=200, null=True)),
                ('subTitleEng', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraphUzb', models.TextField(blank=True, max_length=1000, null=True)),
                ('paragraphRus', models.TextField(blank=True, max_length=1000, null=True)),
                ('paragraphENg', models.TextField(blank=True, max_length=1000, null=True)),
                ('costUzb', models.TextField(blank=True, max_length=1000, null=True)),
                ('costRus', models.TextField(blank=True, max_length=1000, null=True)),
                ('costEng', models.TextField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
