# Generated by Django 3.1.6 on 2021-05-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancys',
            old_name='paragraphENg',
            new_name='paragraphEng',
        ),
    ]
